#!/usr/bin/env bash

sudo apt-get install python3-dev
sudo apt-get install libmysqlclient-dev
sudo apt-get install zlib1g-dev
pip3 install mysqlclient
pip3 install SQLAlchemy
pip3 install Flask
pip install flasgger
